-- Supabase schema for BagTag (Hardhof)
-- Creates players, tags, battles, battle_participants, tag_transfers
-- Idempotent tag seeding for #1..#100

-- Ensure pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create dedicated schema for BagTag objects; keep public untouched
CREATE SCHEMA IF NOT EXISTS bagtag;

-- ==================================================
-- 1) PLAYERS (bagtag.players)
-- ==================================================
CREATE TABLE IF NOT EXISTS bagtag.players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL,
  display_name TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unique username
CREATE UNIQUE INDEX IF NOT EXISTS players_username_unique ON bagtag.players(username);

-- Case-insensitive username search index
CREATE INDEX IF NOT EXISTS players_username_ci_idx ON bagtag.players(LOWER(username));

COMMENT ON TABLE bagtag.players IS 'Persistent player records for BagTag. No current tag stored here; current ownership is tracked in bagtag.tags.owner_id.';
COMMENT ON COLUMN bagtag.players.username IS 'Unique login/username for the player (case-sensitive stored, search supported by LOWER index).';


-- ==================================================
-- 2) TAGS (bagtag.tags)
-- ==================================================
CREATE TABLE IF NOT EXISTS bagtag.tags (
  number SMALLINT PRIMARY KEY,
  owner_id UUID NULL REFERENCES bagtag.players(id),
  assigned_at TIMESTAMPTZ NULL,
  CONSTRAINT tags_number_range CHECK (number BETWEEN 1 AND 100)
);

-- A player can own at most one Tag: partial unique index where owner_id IS NOT NULL
CREATE UNIQUE INDEX IF NOT EXISTS tags_owner_unique ON bagtag.tags(owner_id) WHERE owner_id IS NOT NULL;

COMMENT ON TABLE bagtag.tags IS 'Physical Hardhof Bag Tags #1..#100. The tag number is the canonical identity. Current owner is bagtag.tags.owner_id (NULL = unassigned).';
COMMENT ON COLUMN bagtag.tags.number IS 'Tag identity number 1..100.';


-- ==================================================
-- 3) BATTLES (bagtag.battles)
-- ==================================================
CREATE TABLE IF NOT EXISTS bagtag.battles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  played_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID NULL REFERENCES bagtag.players(id),
  reverted_at TIMESTAMPTZ NULL,
  reverted_by UUID NULL REFERENCES bagtag.players(id)
);

CREATE INDEX IF NOT EXISTS battles_played_at_desc_idx ON bagtag.battles(played_at DESC);

COMMENT ON TABLE bagtag.battles IS 'Confirmed historical battles. Do not delete rows. reverted_at NULL means battle is active.';


-- ==================================================
-- 4) BATTLE_PARTICIPANTS (bagtag.battle_participants)
-- ==================================================
CREATE TABLE IF NOT EXISTS bagtag.battle_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  battle_id UUID NOT NULL REFERENCES bagtag.battles(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES bagtag.players(id),
  player_name_snapshot TEXT NOT NULL,
  score INTEGER NOT NULL,
  position INTEGER NOT NULL,
  starting_tag SMALLINT NOT NULL REFERENCES bagtag.tags(number),
  resulting_tag SMALLINT NOT NULL REFERENCES bagtag.tags(number),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT battle_participant_unique UNIQUE (battle_id, player_id),
  CONSTRAINT battle_participant_score_nonneg CHECK (score >= 0),
  CONSTRAINT battle_participant_position_min CHECK (position >= 1)
);

CREATE INDEX IF NOT EXISTS bp_player_idx ON bagtag.battle_participants(player_id);
CREATE INDEX IF NOT EXISTS bp_battle_idx ON bagtag.battle_participants(battle_id);

COMMENT ON TABLE bagtag.battle_participants IS 'Immutable snapshot rows for each player in a battle. Stores name, starting and resulting tag, score and finishing position.';
COMMENT ON COLUMN bagtag.battle_participants.player_name_snapshot IS 'Player display name at time of battle (snapshot).';


-- ==================================================
-- 5) TAG_TRANSFERS (bagtag.tag_transfers)
-- ==================================================
CREATE TABLE IF NOT EXISTS bagtag.tag_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_number SMALLINT NOT NULL REFERENCES bagtag.tags(number),
  from_player_id UUID NULL REFERENCES bagtag.players(id),
  to_player_id UUID NULL REFERENCES bagtag.players(id),
  battle_id UUID NULL REFERENCES bagtag.battles(id),
  action TEXT NOT NULL,
  created_by UUID NULL REFERENCES bagtag.players(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reason TEXT NULL,
  CONSTRAINT tag_transfers_action_check CHECK (action IN ('battle','admin_assign','admin_unassign','revert'))
);

CREATE INDEX IF NOT EXISTS tt_tag_time_idx ON bagtag.tag_transfers(tag_number, created_at DESC);
CREATE INDEX IF NOT EXISTS tt_from_player_idx ON bagtag.tag_transfers(from_player_id);
CREATE INDEX IF NOT EXISTS tt_to_player_idx ON bagtag.tag_transfers(to_player_id);

COMMENT ON TABLE bagtag.tag_transfers IS 'Chronological history of physical tag ownership changes. Includes battle-driven and admin-driven transfers.';
COMMENT ON COLUMN bagtag.tag_transfers.action IS 'Action type: battle | admin_assign | admin_unassign | revert';


-- ==================================================
-- INDEXES: auxiliary helpful indexes
-- (Some indexes already created inline above)
-- ==================================================

-- Find a tag by owner quickly (partial unique index already enforces single ownership)
CREATE INDEX IF NOT EXISTS tags_owner_idx ON bagtag.tags(owner_id) WHERE owner_id IS NOT NULL;

-- Search players by username (case-insensitive) already provided by players_username_ci_idx

-- ==================================================
-- SEED: ensure tags #1..#100 exist; idempotent
-- ==================================================
INSERT INTO bagtag.tags(number, owner_id, assigned_at)
SELECT gs, NULL, NULL
FROM generate_series(1,100) AS gs
ON CONFLICT (number) DO NOTHING;

-- End of schema
